const db = require('./db');

function init(){db.db.exec(`
CREATE TABLE IF NOT EXISTS rush_profiles (user_id INTEGER PRIMARY KEY,class TEXT NOT NULL DEFAULT 'ᴡᴀʀʀɪᴏʀ',pet TEXT,zone INTEGER NOT NULL DEFAULT 1, title TEXT NOT NULL DEFAULT 'ʀᴜsʜ ᴘʟᴀʏᴇʀ');
CREATE TABLE IF NOT EXISTS rush_zones (id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,reward INTEGER NOT NULL DEFAULT 50,unlock_points INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS rush_pets (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,name TEXT NOT NULL,rarity TEXT NOT NULL DEFAULT 'ᴄᴏᴍᴍᴏɴ',level INTEGER NOT NULL DEFAULT 1, UNIQUE(user_id,name));
CREATE TABLE IF NOT EXISTS rush_event_log (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,reward INTEGER NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS rush_battle_log (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,opponent TEXT NOT NULL,result TEXT NOT NULL,reward INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
`);
const zones=[['ʀᴜsʜ ᴄɪᴛʏ',50,0],['ɢʀᴇᴇɴ ᴠᴀʟʟᴇʏ',100,250],['sᴋʏ ʀᴜɪɴs',175,750],['ʟᴇɢᴇɴᴅ ᴘᴇᴀᴋ',300,1500],['ᴅᴀʀᴋ ᴜɴɪᴠᴇʀsᴇ',500,3000]];
const ins=db.db.prepare('INSERT OR IGNORE INTO rush_zones(name,reward,unlock_points) VALUES(?,?,?)'); zones.forEach(z=>ins.run(...z));
}
function profile(uid){db.db.prepare('INSERT OR IGNORE INTO rush_profiles(user_id) VALUES(?)').run(uid);return db.db.prepare('SELECT * FROM rush_profiles WHERE user_id=?').get(uid)}
function setClass(uid,c){const allowed=['ᴡᴀʀʀɪᴏʀ','ᴀssᴀssɪɴ','sɴɪᴘᴇʀ','ᴍᴀɢᴇ','ᴛᴀɴᴋ'];if(!allowed.includes(c))return {ok:false};profile(uid);db.db.prepare('UPDATE rush_profiles SET class=? WHERE user_id=?').run(c,uid);return {ok:true,class:c}}
function zones(uid){const u=db.getUser(uid);const p=profile(uid);return db.db.prepare('SELECT * FROM rush_zones ORDER BY id').all().map(z=>({...z,unlocked:u&&u.points>=z.unlock_points,owned:z.id<=p.zone}))}
function travel(uid,id){const u=db.getUser(uid);const z=db.db.prepare('SELECT * FROM rush_zones WHERE id=?').get(id);if(!z)return {ok:false,reason:'zone'};if(!u||u.points<z.unlock_points)return {ok:false,reason:'locked',needed:z.unlock_points};profile(uid);db.db.prepare('UPDATE rush_profiles SET zone=? WHERE user_id=?').run(id,uid);return {ok:true,zone:z}}
function addPet(uid,name,rarity='ᴄᴏᴍᴍᴏɴ'){profile(uid);db.db.prepare('INSERT OR IGNORE INTO rush_pets(user_id,name,rarity) VALUES(?,?,?)').run(uid,name,rarity);db.db.prepare('UPDATE rush_profiles SET pet=? WHERE user_id=?').run(name,uid);return true}
function pets(uid){return db.db.prepare('SELECT * FROM rush_pets WHERE user_id=? ORDER BY level DESC,id').all(uid)}
function battle(uid,mode='ᴅᴜᴇʟ'){const u=db.getUser(uid);if(!u)return {ok:false};const p=profile(uid);const classes={ᴡᴀʀʀɪᴏʀ:1.08,ᴀssᴀssɪɴ:1.16,sɴɪᴘᴇʀ:1.2,ᴍᴀɢᴇ:1.25,ᴛᴀɴᴋ:1.12};const power=(classes[p.class]||1)*(p.zone||1);const win=Math.random()<Math.min(.88,.48+power*.05);const reward=win?(25+(p.zone-1)*20):0;if(win)db.db.prepare('UPDATE users SET points=points+? WHERE user_id=?').run(reward,uid);db.db.prepare('INSERT INTO rush_battle_log(user_id,opponent,result,reward) VALUES(?,?,?,?)').run(uid,mode,win?'ᴡɪɴ':'ʟᴏss',reward);return {ok:true,win,reward,class:p.class,zone:p.zone}}
function game(uid,game){const u=db.getUser(uid);if(!u)return {ok:false};let reward=0,win=false;if(game==='ᴡʜᴇᴇʟ'){reward=[0,10,20,50,100,200][Math.floor(Math.random()*6)];win=reward>0}else if(game==='ᴅɪᴄᴇ'){const a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);win=a>b;reward=win?30:0}else if(game==='sʟᴏᴛs'){const a=1+Math.floor(Math.random()*7),b=1+Math.floor(Math.random()*7),c=1+Math.floor(Math.random()*7);win=a===b&&b===c;reward=win?250:(a===b||b===c||a===c?25:0)}else if(game==='ᴍɪɴᴇs'){win=Math.random()>.35;reward=win?40:0}else return {ok:false};if(reward)db.db.prepare('UPDATE users SET points=points+? WHERE user_id=?').run(reward,uid);return {ok:true,win,reward,game}}
function dailyEvent(uid){const today=new Date().toISOString().slice(0,10);const key='ᴅᴀɪʟʏ ʀᴜsʜ';const row=db.db.prepare('SELECT * FROM rush_event_log WHERE title=? AND date(created_at)=?').get(key,today);if(!row)db.db.prepare('INSERT INTO rush_event_log(title,reward) VALUES(?,?)').run(key,250);const claimed=db.db.prepare('SELECT 1 FROM point_transactions WHERE user_id=? AND reason=? AND reference=?').get(uid,'rush_event',today);if(claimed)return {ok:false};db.db.prepare('UPDATE users SET points=points+250 WHERE user_id=?').run(uid);db.db.prepare('INSERT INTO point_transactions(user_id,amount,reason,reference) VALUES(?,?,?,?,?)').run(uid,250,'rush_event',today);return {ok:true,reward:250}}
function adminStats(){return {players:db.db.prepare('SELECT COUNT(*) n FROM users').get().n,points:db.db.prepare('SELECT COALESCE(SUM(points),0) n FROM users').get().n,pets:db.db.prepare('SELECT COUNT(*) n FROM rush_pets').get().n,battles:db.db.prepare('SELECT COUNT(*) n FROM rush_battle_log').get().n}}
init();module.exports={profile,setClass,zones,travel,pets,addPet,battle,game,dailyEvent,adminStats};
